apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: golang-sample
  namespace: openshift-lab
  labels:
    app: golang-sample
    app.kubernetes.io/part-of: openshift-lab
spec:
  output:
    to:
      kind: ImageStreamTag
      name: golang-sample:latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  source:
    git:
      ref: develop
      uri: https://github.ibm.com/robson-neto/openshift-lab.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.18-ubi9
        namespace: openshift
    type: Source
  triggers:
    - type: ConfigChange
